version: "3"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - .env
    volumes:
      - ./mountPoint/config:/config
      - ./mountPoint/modules:/lib/modules
      - ./scripts:/scripts
    ports:
      - ${SERVERPORT}:${SERVERPORT}/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
